# view /docs/CONTRIBUTING.md and make a PR
# to add your blog post to our list!

feeds = [
    "https://salm.dev/rss.xml",
    "https://ben.enterprises/rss.xml",
    "https://www.amoses.dev/rss.xml",
    "https://nick.winans.io/rss.xml",
    "https://dteather.com/blogs/rss.xml",
    "https://bytesnotborders.com/feed.xml",
    "https://www.noguera.dev/blog/index.xml",
]
